
# 1. Pixabay API

# GET https://pixabay.com/api/?key=14956666-5f488f59d788ad507536dbbad&q=patna

# Response-
# data.hits[0].largeImageURL

# 2. GeoNames API
# GET   http://api.geonames.org/searchJSON?q=patna&maxRows=1&username=shubhamprakash

# Response
# geonames[0].lat
# geonames[0].lng






# 3. DarkSky API

# GET https://api.darksky.net/forecast/e32200291377f81b23312e8c40d3677e/25.47241,89.53291







GET http://localhost:8000/trip HTTP/1.1


##post

# POST http://localhost:8000/trip HTTP/1.1
# Content-Type: application/json

# {
#   "place":"patna 3",
#   "date":"2020.01.22",
#   "note": "Hellow world 3"
# }


# Delete

# POST http://localhost:8000/delete/ HTTP/1.1
# Content-Type: application/json

# {
#   "id":"2"
# }